### PR TITLE
Say hello

### PR DESCRIPTION
**Pull request by yunjison10**

### CODE REVIEW

**Comment by yunjison10** [comment]
I don't merge this request yet to show to instructor for the grading as opening merge request is my submission for lab #4

**Comment by pochin345** [comment]
Your work looks good.  Please complete the pull request.

**Review by pochin345 — COMMENTED** [review]
You want to place the class header (Java doc) just before the class signature, not before the package and imports

**Comment by yunjison10** [comment]
Thanks for useful comment. I will keep it. Thanks!

**Pull request closed without merging**
